### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by hearnsj** [JuliaHealth/DICOMClient.jl#17]
This is a great project. I have worked with DICOM servers, CT and MRI sources in the past (20 years ago). I recently worked with one of the public domain DICOM servers also, in a company which was applying deep learning to mammography. Sorry I cannot offer to do any real world testing.

The issue is that the documentation link is nor working. Sorry!

**Comment by DilumAluthge** [comment]
The link should be working now.

**Comment by DilumAluthge** [comment]
@hearnsj When you have a chance, can you see if the documentation link is working for you now?

**Comment by hearnsj** [comment]
The documentation link is working.

I can offer to help with testing with this server running locally  https://www.orthanc-server.com/

**Comment by DilumAluthge** [comment]
That would be great! I appreciate all the help I can get.
